/**
 * E2E Cross-Process P2P Worker DM Test
 *
 * These tests prove that two *separate Node.js processes* operating on the same
 * filesystem can exchange messages without sharing in-memory state — the exact
 * scenario that occurs when real `claude -p` workers each spin up their own
 * coordinator instance.
 *
 * Unlike p2p-messaging.test.mjs (which calls the coordinator in-process), each
 * test here spawns a real child subprocess that:
 *   1. Sets HOME to a temp directory
 *   2. Imports the coordinator from an absolute file URL
 *   3. Calls handleToolCall('coord_send_message', ...)
 *   4. Writes the JSON result to stdout
 *
 * We then read the inbox JSONL file on disk and assert the message arrived
 * across the process boundary.
 *
 * Coverage:
 *   1. Subprocess sends DM to peer → JSONL inbox contains message with correct from/content
 *   2. Sender's own inbox is unmodified after a DM send (message goes TO target, not FROM)
 *   3. Unknown target_name → subprocess exits cleanly, error returned in tool result
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import {
  mkdtempSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  existsSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Absolute file URL for the coordinator — works regardless of where the
// subprocess script is written on disk.
const COORD_INDEX_URL = pathToFileURL(join(__dirname, '..', 'index.js')).href;

// ─── Helpers (mirrored from p2p-messaging.test.mjs) ──────────────────────────

/**
 * Build a minimal temp HOME with the directory layout the coordinator expects.
 */
function setupHome() {
  const home = mkdtempSync(join(tmpdir(), 'coord-e2e-dm-'));
  const terminals = join(home, '.claude', 'terminals');
  const inbox = join(terminals, 'inbox');
  const results = join(terminals, 'results');
  mkdirSync(inbox, { recursive: true });
  mkdirSync(results, { recursive: true });
  mkdirSync(join(home, '.claude', 'session-cache'), { recursive: true });
  return { home, terminals, inbox, results };
}

/**
 * Register a worker by writing a session file — exactly what the heartbeat
 * hook writes in production. resolveWorkerName() reads these files.
 */
function registerWorker(terminals, inbox, sessionId, workerName) {
  writeFileSync(
    join(terminals, `session-${sessionId}.json`),
    JSON.stringify({
      session: sessionId,
      worker_name: workerName,
      status: 'active',
      last_active: new Date().toISOString(),
      cwd: '/tmp/project',
      project: 'test-project',
    }),
  );
  // Pre-create the inbox file so appendJSONLineSecure can write without creating it
  writeFileSync(join(inbox, `${sessionId}.jsonl`), '');
}

/**
 * Build the ESM source code for a subprocess that sends one DM.
 * Accepts SENDER_NAME, TARGET_NAME, MESSAGE_CONTENT via env vars so the
 * same script template is reusable across tests.
 */
function buildSenderScript(coordUrl) {
  return `// Auto-generated by e2e-p2p-worker-dm.test.mjs
process.env.HOME = process.env.TEST_HOME;
process.env.COORDINATOR_TEST_MODE = '1';
process.env.COORDINATOR_PLATFORM = 'linux';

const mod = await import(${JSON.stringify(coordUrl)});
const api = mod.__test__;
api.ensureDirsOnce();

const result = api.handleToolCall('coord_send_message', {
  from: process.env.SENDER_NAME,
  target_name: process.env.TARGET_NAME,
  content: process.env.MESSAGE_CONTENT,
});

process.stdout.write(JSON.stringify(result) + '\\n');
`;
}

/**
 * Run the sender subprocess synchronously and return { status, result, stderr }.
 * Throws a descriptive error if the subprocess crashes.
 */
function runSender(home, { sender, target, content }) {
  const scriptPath = join(home, `subprocess-${Date.now()}.mjs`);
  writeFileSync(scriptPath, buildSenderScript(COORD_INDEX_URL));

  const out = spawnSync(process.execPath, [scriptPath], {
    env: {
      ...process.env,
      TEST_HOME: home,
      COORDINATOR_TEST_MODE: '1',
      COORDINATOR_PLATFORM: 'linux',
      SENDER_NAME: sender,
      TARGET_NAME: target,
      MESSAGE_CONTENT: content,
    },
    encoding: 'utf8',
    timeout: 15_000,
  });

  return {
    status: out.status,
    stdout: out.stdout,
    stderr: out.stderr,
    result: out.stdout.trim() ? JSON.parse(out.stdout.trim()) : null,
  };
}

// ─── Tests ────────────────────────────────────────────────────────────────────

test('cross-process: worker-a sends DM to worker-b, inbox receives message', () => {
  const { home, terminals, inbox } = setupHome();

  const aId = 'a1a1a1a1';
  const bId = 'b2b2b2b2';
  registerWorker(terminals, inbox, aId, 'worker-a');
  registerWorker(terminals, inbox, bId, 'worker-b');

  const { status, result, stderr } = runSender(home, {
    sender: 'worker-a',
    target: 'worker-b',
    content: 'ping',
  });

  assert.strictEqual(
    status,
    0,
    `Subprocess exited with code ${status}\nSTDERR: ${stderr}`,
  );

  // Tool call result should confirm delivery
  const txt = result?.content?.[0]?.text ?? '';
  assert.match(txt, /Message sent/i, 'Tool result must confirm message was sent');
  assert.match(txt, new RegExp(bId), 'Tool result must mention target session ID');

  // The target's inbox JSONL file must contain the message
  const bInboxPath = join(inbox, `${bId}.jsonl`);
  assert.ok(existsSync(bInboxPath), 'Target inbox file must exist on disk');

  const raw = readFileSync(bInboxPath, 'utf8').trim();
  assert.ok(raw.length > 0, 'Target inbox must not be empty after send');

  const msg = JSON.parse(raw.split('\n')[0]);
  assert.strictEqual(msg.from, 'worker-a', 'msg.from must be the sending worker');
  assert.match(msg.content, /ping/i, 'msg.content must contain the sent text');
});

test('cross-process: sender inbox is untouched after DM send', () => {
  const { home, terminals, inbox } = setupHome();

  const aId = 'c3c3c3c3';
  const bId = 'd4d4d4d4';
  registerWorker(terminals, inbox, aId, 'worker-a');
  registerWorker(terminals, inbox, bId, 'worker-b');

  const { status, stderr } = runSender(home, {
    sender: 'worker-a',
    target: 'worker-b',
    content: 'hello from subprocess',
  });

  assert.strictEqual(status, 0, `Subprocess failed:\n${stderr}`);

  // Sender's own inbox must be empty — message goes TO target, not back to sender
  const aInboxRaw = readFileSync(join(inbox, `${aId}.jsonl`), 'utf8');
  assert.strictEqual(aInboxRaw, '', 'Sender inbox must be empty after DM send');

  // Recipient's inbox must have the message
  const bInboxRaw = readFileSync(join(inbox, `${bId}.jsonl`), 'utf8').trim();
  assert.ok(bInboxRaw.length > 0, 'Recipient inbox must contain the message');

  const msg = JSON.parse(bInboxRaw.split('\n')[0]);
  assert.match(msg.content, /hello from subprocess/i, 'Message content must round-trip correctly');
});

test('cross-process: unknown target_name returns error, subprocess exits cleanly', () => {
  const { home, terminals, inbox } = setupHome();

  registerWorker(terminals, inbox, 'e5e5e5e5', 'worker-a');
  // Intentionally do NOT register 'ghost-worker' — it shouldn't exist

  const { status, result, stderr } = runSender(home, {
    sender: 'worker-a',
    target: 'ghost-worker',
    content: 'this should fail gracefully',
  });

  // Subprocess must exit cleanly — coordinator must not throw/crash
  assert.strictEqual(
    status,
    0,
    `Subprocess must exit 0 even on unknown target\nSTDERR: ${stderr}`,
  );

  // Tool result must contain a meaningful error message
  const txt = result?.content?.[0]?.text ?? '';
  assert.match(txt, /not found/i, 'Error message must say target was not found');
  assert.match(
    txt,
    /ghost-worker/i,
    'Error message must echo back the unknown target name',
  );
});
